version: '3.8'
#UPDATED 2/8
services:

  config-service:
    container_name: config-service
    image: genarorichard/config-service:v1.0
    ports:
      - "8000:8000"
    environment:
      EUREKA_HOST: eureka-service

    networks:
      - waddler-network

  eureka-service:
    container_name: eureka-service
    image: genarorichard/eureka-service:last
    environment:
      CONFIG_SERVICE_HOST: config-service
    ports:
      - "8761:8761"

    networks:
      - waddler-network


  gateway-service:
    container_name: gateway-service
    image: genarorichard/gateway-service:last
    ports:
      - "8081:8081"
    environment:
      CONFIG_SERVICE_HOST: config-service
      KEYCLOAK_HOST: keycloak
      EUREKA_HOST: eureka-service
      KEYCLOAK_INTERNAL_HOST: keycloak

      CLIENT_SECRET: 9xXfqVsbcMvxdIlhx3oKO43b6pyeUoMN
    networks:
      - waddler-network

  multi-rubro-project:
    container_name: multi-rubro-project
    image: genarorichard/multirubro:last
    environment:
      CONFIG_SERVICE_URL: config-service
      KEYCLOAK_HOST: keycloak
      EUREKA_HOST: eureka-service
      KEYCLOAK_INTERNAL_HOST: keycloak
      RABBITMQ_HOST: rabbitmq
      CLIENT_SECRET: 9xXfqVsbcMvxdIlhx3oKO43b6pyeUoMN
    networks:
      - waddler-network

  mysql-database:
    image: mysql:latest
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: keycloak
      MYSQL_USER: waddler
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql_data_keycloak:/var/lib/mysql_keycloak
    networks:
      - waddler-network

  mysql-database-multirubro:
    image: mysql:latest
    container_name: mysql-database-multirubro
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: multirubro
      MYSQL_USER: waddler
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql_data_multirubro:/var/lib/mysql_multirubro
    networks:
      - database-multirubro

  mysql-database-multirubroproducts:
    image: mysql:latest
    container_name: mysql-database-multirubroproducts
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: multirubroproducts
      MYSQL_USER: waddler
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - /var/lib/mysql_data_multirubroproducts:/var/lib/mysql_multirubroproducts
    networks:
      - database-multirubroproducts

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.2
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-database:3306/keycloak    # Use the service name of MySQL container here
      KC_DB_USERNAME: waddler
      KC_DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_PROFILE: dev
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - mysql-database
    networks:
      - waddler-network
    command: start-dev

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - waddler-network



volumes:
  rabbitmq_data:
  rabbitmq_logs:


networks:
  waddler-network:
    driver: bridge
  database-multirubro:
    driver: bridge
  database-multirubroproducts:
    driver: bridge

