server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: multi-rubro-project-bills
          uri: lb://multi-rubro-project
          predicates:
            - Path=/bills/**
        - id: multi-rubro-project-clients
          uri: lb://multi-rubro-project
          predicates:
            - Path=/clients/**
        - id: multi-rubro-project-sellings
          uri: lb://multi-rubro-project
          predicates:
            - Path=/sellings/**
        - id: multi-rubro-project-users
          uri: lb://multi-rubro-project
          predicates:
            - Path=/users/**





