server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA_HOST}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}



#SPRING DOC PROPERTIES


#DATABASE CONFIG
spring:
  datasource:
    url: jdbc:mysql://mysql-database-multirubro:3306/multirubroproducts
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: waddler
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  application:


  h2:
    console:
      enabled: false
      path: /h2-console

