server:
  port: 8085



#DATABASE CONFIG
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console


  #RABBITMQ CONFIG
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
